import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting seed...");

  // ─── Projects ──────────────────────────────────────────────────────────────
  await prisma.project.deleteMany();
  await prisma.project.createMany({
    data: [
      {
        id: "nexus-ai-support-platform",
        slug: "nexus-ai-support-platform",
        category: "AI",
        client: "Enterprise SaaS Client",
        location: "Kuwait City, Kuwait",
        year: "2025",
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Nexus AI Support Platform",
        titleAr: "منصة Nexus للدعم بالذكاء الاصطناعي",
        summaryEn: "An AI support platform combining a natural-language query engine with a real-time chatbot that resolves customer questions and surfaces live business data.",
        summaryAr: "منصة دعم بالذكاء الاصطناعي تجمع بين محرك استعلامات بلغة طبيعية ومحادثة آلية فورية تحل استفسارات العملاء وتوفر بيانات أعمال حية.",
        deliverablesEn: ["Text-to-SQL engine", "Multi-agent orchestration", "Real-time chatbot", "Analytics dashboard"],
        deliverablesAr: ["محرك تحويل النص إلى استعلام SQL", "تنسيق وكلاء متعددين", "محادثة آلية فورية", "لوحة تحليلات"],
        featured: true,
        sortOrder: 1,
      },
      {
        id: "al-essa-medical-platform",
        slug: "al-essa-medical-platform",
        category: "E-commerce",
        client: "Al-Essa Healthcare Group",
        location: "Kuwait City, Kuwait",
        year: "2025",
        image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Al-Essa Medical Commerce",
        titleAr: "منصة الإيصاء الطبية للتجارة الإلكترونية",
        summaryEn: "A custom e-commerce platform with KNET integration, built for a leading Kuwait medical supplier.",
        summaryAr: "منصة تجارة إلكترونية مخصصة مع دمج بوابة كي نت، أُنجزت لمورد طبي رائد في الكويت.",
        deliverablesEn: ["E-commerce platform", "KNET payment hub", "Inventory sync", "Mobile web app"],
        deliverablesAr: ["منصة تجارة إلكترونية", "مركز دفع كي نت", "مزامنة المخزون", "تطبيق ويب للجوال"],
        featured: true,
        sortOrder: 2,
      },
      {
        id: "skinnovation-beauty-app",
        slug: "skinnovation-beauty-app",
        category: "App",
        client: "Skinnovation Clinic",
        location: "Salmiya, Kuwait",
        year: "2025",
        image: "https://images.unsplash.com/photo-1556760544-74068565f05c?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Skinnovation Clinic App",
        titleAr: "تطبيق عيادة Skinnovation",
        summaryEn: "An iOS and Android booking app for appointment scheduling, consultation history, and loyalty rewards.",
        summaryAr: "تطبيق حجز لنظامي iOS و Android لجدولة المواعيد وسجل الاستشارات وبرنامج الولاء.",
        deliverablesEn: ["iOS & Android app", "UI/UX system", "Appointment engine", "Push notifications"],
        deliverablesAr: ["تطبيق iOS و Android", "نظام واجهة وتجربة مستخدم", "محرك حجز المواعيد", "إشعارات فورية"],
        featured: true,
        sortOrder: 3,
      },
      {
        id: "virtus-corporate-identity",
        slug: "virtus-corporate-identity",
        category: "Branding",
        client: "Virtus Holding",
        location: "Kuwait",
        year: "2024",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Virtus Brand System",
        titleAr: "هوية Virtus التجارية",
        summaryEn: "A rebrand for Virtus Group covering typography, stationery, digital assets, and brand guidelines.",
        summaryAr: "إعادة تصميم هوية مجموعة Virtus شملت الطباعة والقرطاسية والأصول الرقمية ودليل الهوية.",
        deliverablesEn: ["Logo & visual identity", "Brand guidelines", "Stationery kit", "Digital assets"],
        deliverablesAr: ["شعار وهوية بصرية", "دليل الهوية", "طقم قرطاسية", "أصول رقمية"],
        featured: true,
        sortOrder: 4,
      },
      {
        id: "waseet-pools-web-portal",
        slug: "waseet-pools-web-portal",
        category: "Web",
        client: "Waseet Pools Co.",
        location: "Shuwaikh, Kuwait",
        year: "2024",
        image: "https://images.unsplash.com/photo-1572331165267-854da2b10ccc?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Waseet Pools Corporate Web",
        titleAr: "موقع وسيط المسابح الإلكتروني",
        summaryEn: "A marketing website with localized SEO that grew organic lead conversions by 140%.",
        summaryAr: "موقع تسويقي مع تحسين محركات بحث محلي رفع تحويلات العملاء المحتملين العضوية بنسبة 140%.",
        deliverablesEn: ["Next.js website", "SEO campaign", "Lead generation form", "CMS"],
        deliverablesAr: ["موقع Next.js", "حملة تحسين محركات البحث", "نموذج توليد العملاء المحتملين", "نظام إدارة محتوى"],
        featured: true,
        sortOrder: 5,
      },
      {
        id: "kerala-restaurant-group",
        slug: "kerala-restaurant-group",
        category: "App",
        client: "Kerala Express Group",
        location: "Hawally, Kuwait",
        year: "2024",
        image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Kerala Express Mobile Ordering",
        titleAr: "تطبيق طلبات Kerala Express",
        summaryEn: "A food ordering app for iOS and Android with live order tracking and multi-branch menu routing.",
        summaryAr: "تطبيق طلب طعام لنظامي iOS و Android مع تتبع الطلبات الحي وتوجيه القوائم متعددة الفروع.",
        deliverablesEn: ["Mobile app", "POS integration", "WhatsApp notifications"],
        deliverablesAr: ["تطبيق جوال", "ربط نقاط البيع", "إشعارات واتساب"],
        featured: false,
        sortOrder: 6,
      },
      {
        id: "vintage-poster-editorial",
        slug: "vintage-poster-editorial",
        category: "Branding",
        client: "Burhani Creative Showcase",
        location: "Hawally, Kuwait",
        year: "2024",
        image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Vintage Poster & Graphic Art",
        titleAr: "ملصقات وأعمال فنية بطابع كلاسيكي",
        summaryEn: "A print and digital poster collection combining classical typography with contemporary Gulf motifs.",
        summaryAr: "مجموعة ملصقات مطبوعة ورقمية تجمع بين الطباعة الكلاسيكية وموتيفات خليجية معاصرة.",
        deliverablesEn: ["Graphic design", "Print mockups", "Typography"],
        deliverablesAr: ["تصميم جرافيك", "نماذج طباعة", "طباعة نصية"],
        featured: false,
        sortOrder: 7,
      },
      {
        id: "glued-poster-mockup-series",
        slug: "glued-poster-mockup-series",
        category: "Web",
        client: "Metropolitan Urban Series",
        location: "Kuwait City",
        year: "2023",
        image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop",
        titleEn: "Glued Poster Campaign",
        titleAr: "حملة الملصقات اللاصقة",
        summaryEn: "A web gallery showcasing urban design projects and outdoor marketing mockups.",
        summaryAr: "معرض ويب لمشاريع تصميم حضري ونماذج تسويق خارجي.",
        deliverablesEn: ["Web gallery", "Interactive UI", "Animation"],
        deliverablesAr: ["معرض ويب", "واجهة تفاعلية", "رسوم متحركة"],
        featured: false,
        sortOrder: 8,
      },
    ],
  });
  console.log("✅ Projects seeded");

  // ─── Services ─────────────────────────────────────────────────────────────
  await prisma.service.deleteMany();
  await prisma.service.createMany({
    data: [
      {
        id: "mobile-app-development",
        slug: "mobile-app-development",
        iconName: "Smartphone",
        image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?q=80&w=900&auto=format&fit=crop",
        accent: "#2563eb",
        titleEn: "Mobile App Development",
        titleAr: "تطوير تطبيقات الجوال",
        taglineEn: "Native iOS and Android apps built for performance and growth.",
        taglineAr: "تطبيقات iOS و Android أصلية مبنية للأداء والنمو.",
        descriptionEn: "Custom app development for iOS and Android, with an interactive prototype shared before development starts so every feature matches your goals.",
        descriptionAr: "تطوير تطبيقات مخصصة لنظامي iOS و Android، مع نموذج أولي تفاعلي يُعرض قبل بدء التطوير لضمان توافق كل ميزة مع أهداف عملك.",
        fullDescriptionEn: "We design and build fast, reliable mobile applications for iOS and Android — from the first wireframe through backend integration and submission to the App Store and Google Play.",
        fullDescriptionAr: "نصمم ونبني تطبيقات جوال سريعة وموثوقة لنظامي iOS و Android — من أول مخطط أولي وحتى ربط الأنظمة الخلفية والنشر على App Store و Google Play.",
        deliverablesEn: ["iOS app (Swift / React Native)", "Android app (Kotlin / React Native)", "Interactive prototype & UI specs", "API & backend integration", "App Store & Play Store submission"],
        deliverablesAr: ["تطبيق iOS (بلغة Swift أو React Native)", "تطبيق Android (بلغة Kotlin أو React Native)", "نموذج أولي تفاعلي ومواصفات الواجهة", "ربط واجهات برمجة التطبيقات والأنظمة الخلفية", "النشر على المتاجر"],
        featuresEn: ["Iterative sprints with working previews", "Optimized for phones and tablets", "Secure payment integration", "Push notifications & analytics"],
        featuresAr: ["مراحل عمل تكرارية مع معاينات فعلية", "متوافق مع الهواتف والأجهزة اللوحية", "دمج آمن لبوابات الدفع", "إشعارات فورية وتحليلات استخدام"],
        techStack: ["React Native", "Flutter", "Swift", "Kotlin", "Node.js", "Firebase"],
        sortOrder: 1,
      },
      {
        id: "website-development",
        slug: "website-development",
        iconName: "Globe",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=900&auto=format&fit=crop",
        accent: "#0891b2",
        titleEn: "Website Development",
        titleAr: "تطوير المواقع الإلكترونية",
        taglineEn: "Fast, modern websites built to convert.",
        taglineAr: "مواقع إلكترونية سريعة وحديثة مبنية لتحقيق التحويلات.",
        descriptionEn: "Responsive web applications built on modern frameworks, designed to increase conversion and build trust across Gulf industries.",
        descriptionAr: "تطبيقات ويب متجاوبة مبنية على أطر عمل حديثة، مصممة لرفع معدلات التحويل وبناء الثقة في مختلف القطاعات الخليجية.",
        fullDescriptionEn: "Your website is your primary digital asset. We build responsive, high-performance web applications on Next.js, Node.js, and TypeScript — engineered for speed, search visibility, security, and easy day-to-day management.",
        fullDescriptionAr: "موقعك الإلكتروني هو أصلك الرقمي الأساسي. نبني تطبيقات ويب متجاوبة وعالية الأداء باستخدام Next.js و Node.js و TypeScript — مصممة للسرعة وتحسين محركات البحث والأمان وسهولة الإدارة اليومية.",
        deliverablesEn: ["Custom Next.js web application", "Responsive desktop & mobile layouts", "Headless CMS / content layer", "SEO setup & analytics", "Performance & security review"],
        deliverablesAr: ["تطبيق ويب مخصص على Next.js", "تصميم متجاوب لسطح المكتب والجوال", "نظام إدارة محتوى منفصل", "إعداد تحسين محركات البحث والتحليلات", "مراجعة الأداء والأمان"],
        featuresEn: ["Sub-second load times, 95+ Lighthouse score", "Mobile-first layout", "Structured data for search engines", "Custom interactive components"],
        featuresAr: ["زمن تحميل أقل من ثانية وتقييم Lighthouse فوق 95", "تصميم يبدأ من الجوال أولاً", "بيانات منظمة لمحركات البحث", "مكونات تفاعلية مخصصة"],
        techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js", "GraphQL", "PostgreSQL"],
        sortOrder: 2,
      },
      {
        id: "e-commerce-development",
        slug: "e-commerce-development",
        iconName: "ShoppingBag",
        image: "/ecommerce-cover.png",
        accent: "#d97706",
        titleEn: "E-Commerce Development",
        titleAr: "تطوير التجارة الإلكترونية",
        taglineEn: "Online stores built to convert and scale.",
        taglineAr: "متاجر إلكترونية مبنية للتحويل والنمو.",
        descriptionEn: "Online stores for web and mobile on Shopify, WooCommerce, or a custom headless platform, with local payment integration and room to grow.",
        descriptionAr: "متاجر إلكترونية للويب والجوال عبر Shopify أو WooCommerce أو منصة مخصصة، مع دمج بوابات الدفع المحلية وقابلية للتوسع.",
        fullDescriptionEn: "We build scalable, conversion-focused online stores. From local Gulf payment gateways (KNET, MyFatoorah, Tap) to multi-currency support and inventory sync, we cover what's needed to sell online at scale.",
        fullDescriptionAr: "نبني متاجر إلكترونية قابلة للتوسع تركز على التحويل. من بوابات الدفع الخليجية المحلية (كي نت، ماي فاتورة، تاب) إلى دعم العملات المتعددة ومزامنة المخزون، نوفر كل ما يلزم للبيع عبر الإنترنت على نطاق واسع.",
        deliverablesEn: ["Custom storefront & checkout", "KNET / Gulf payment gateway", "Inventory & order management", "Customer accounts & order tracking", "Abandoned cart recovery"],
        deliverablesAr: ["واجهة متجر وصفحة دفع مخصصة", "بوابة دفع كي نت أو خليجية", "إدارة المخزون والطلبات", "حسابات العملاء وتتبع الطلبات", "استرجاع عربات التسوق المتروكة"],
        featuresEn: ["KNET, MyFatoorah, and Tap integration", "Instant search & filtering", "Automated WhatsApp order updates", "Arabic / English ready"],
        featuresAr: ["دمج كي نت وماي فاتورة وتاب", "بحث فوري وتصفية ذكية", "تحديثات طلبات تلقائية عبر واتساب", "جاهزية كاملة للعربية والإنجليزية"],
        techStack: ["Shopify Plus", "Next.js Commerce", "WooCommerce", "Stripe", "KNET", "MyFatoorah"],
        sortOrder: 3,
      },
      {
        id: "ui-ux-design",
        slug: "ui-ux-design",
        iconName: "Layout",
        image: "https://images.unsplash.com/photo-1559028006-448665bd7c7f?q=80&w=900&auto=format&fit=crop",
        accent: "#db2777",
        titleEn: "UI/UX Design",
        titleAr: "تصميم واجهات وتجربة المستخدم",
        taglineEn: "Interface design grounded in research, not templates.",
        taglineAr: "تصميم واجهات مبني على البحث، لا على القوالب الجاهزة.",
        descriptionEn: "Interface design for web and mobile, grounded in user research and built for clarity across Kuwait and the Gulf.",
        descriptionAr: "تصميم واجهات للويب والجوال مبني على بحث المستخدم وواضح الأسلوب، لعملاء في الكويت والخليج.",
        fullDescriptionEn: "Good design communicates clearly. Our team runs user research, builds interactive Figma prototypes, and establishes a design system so the product stays consistent — and a pleasure to use — end to end.",
        fullDescriptionAr: "التصميم الجيد يوصل الفكرة بوضوح. يجري فريقنا أبحاث المستخدمين، ويبني نماذج أولية تفاعلية على Figma، ويؤسس نظام تصميم متكامل يجعل المنتج متسقًا وسهل الاستخدام من البداية للنهاية.",
        deliverablesEn: ["User journey & architecture maps", "High-fidelity Figma wireframes", "Interactive clickable prototypes", "Brand design system & tokens", "Usability testing & refinement"],
        deliverablesAr: ["خرائط رحلة المستخدم وبنية المعلومات", "نماذج Figma عالية الدقة", "نماذج أولية تفاعلية قابلة للنقر", "نظام تصميم الهوية ومكوناته", "اختبار قابلية الاستخدام والتحسين"],
        featuresEn: ["Clean, editorial typography", "Accessible by default", "Design-to-code handoff", "RTL (Arabic) layout support"],
        featuresAr: ["طباعة نظيفة بأسلوب تحريري", "إتاحة الوصول بشكل افتراضي", "تسليم مباشر من التصميم إلى الكود", "دعم تخطيط RTL للعربية"],
        techStack: ["Figma", "Framer", "Adobe CC", "Design Systems", "Prototyping"],
        sortOrder: 4,
      },
      {
        id: "erp-solutions",
        slug: "erp-solutions",
        iconName: "Database",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=900&auto=format&fit=crop",
        accent: "#059669",
        titleEn: "ERP Solutions",
        titleAr: "حلول تخطيط موارد المؤسسات",
        taglineEn: "Business software built around how you actually work.",
        taglineAr: "أنظمة إدارية مبنية على طريقة عملك الفعلية.",
        descriptionEn: "Business software for retail, corporate, and trading operations — scalable, localized, and built around your daily workflow in Kuwait.",
        descriptionAr: "برمجيات إدارية للتجزئة والشركات والتجارة — قابلة للتوسع ومحلية ومبنية حول سير عملك اليومي في الكويت.",
        fullDescriptionEn: "Centralize your operations with an ERP built for your business. We design and deploy point-of-sale, inventory management, invoicing, HR, accounting, and supply chain tracking in one system.",
        fullDescriptionAr: "مركّز عملياتك في نظام ERP مصمم لعملك. نصمم وننشر نقاط البيع وإدارة المخزون والفوترة والموارد البشرية والمحاسبة وتتبع سلسلة التوريد في نظام واحد.",
        deliverablesEn: ["Custom ERP platform", "Inventory & stock tracking", "Point of sale & invoicing", "HR & payroll management", "Financial reporting & dashboards"],
        deliverablesAr: ["منصة ERP مخصصة", "تتبع المخزون والمستودعات", "نقاط البيع والفوترة", "إدارة الموارد البشرية والرواتب", "تقارير مالية ولوحات بيانات"],
        featuresEn: ["Kuwait tax & invoicing formats", "Role-based access & permissions", "Cloud access from any device", "Custom reports & exports"],
        featuresAr: ["صيغ ضريبة وفوترة كويتية", "صلاحيات وصول حسب الدور", "وصول سحابي من أي جهاز", "تقارير وتصدير بيانات مخصصة"],
        techStack: ["Node.js", "Python", "PostgreSQL", "Docker", "Tailwind UI", "REST APIs"],
        sortOrder: 5,
      },
      {
        id: "ai-solutions",
        slug: "ai-solutions",
        iconName: "Sparkles",
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=900&auto=format&fit=crop",
        accent: "#7c3aed",
        titleEn: "AI Solutions",
        titleAr: "حلول الذكاء الاصطناعي",
        taglineEn: "Practical AI that answers, automates, and predicts.",
        taglineAr: "ذكاء اصطناعي عملي يجيب ويؤتمت ويتنبأ.",
        descriptionEn: "Custom AI assistants, chatbots, and data engines that plug into your business — from natural-language search to automated workflows.",
        descriptionAr: "مساعدون أذكياء ومحادثات آلية ومحركات بيانات مخصصة تندمج مع عملك — من البحث بلغة طبيعية إلى أتمتة سير العمل.",
        fullDescriptionEn: "We build AI features that solve real business problems: support chatbots trained on your content, text-to-SQL query engines, document processing, and multi-agent automation — integrated with the tools your team already uses, in Arabic and English.",
        fullDescriptionAr: "نبني ميزات ذكاء اصطناعي تحل مشكلات أعمال حقيقية: محادثات دعم مدرَّبة على محتواك، ومحركات تحويل النص إلى استعلام SQL، ومعالجة المستندات، وأتمتة متعددة الوكلاء — مدمجة مع الأدوات التي يستخدمها فريقك بالفعل، بالعربية والإنجليزية.",
        deliverablesEn: ["AI chatbot & assistant", "Natural-language data search", "Document & workflow automation", "Model & prompt engineering", "Secure private deployment"],
        deliverablesAr: ["محادثة ومساعد ذكي", "بحث في البيانات بلغة طبيعية", "أتمتة المستندات وسير العمل", "هندسة النماذج والأوامر", "نشر خاص وآمن"],
        featuresEn: ["Trained on your own data", "Arabic & English understanding", "Human-in-the-loop controls", "Analytics on every conversation"],
        featuresAr: ["مدرَّب على بياناتك الخاصة", "فهم للعربية والإنجليزية", "تحكم بإشراف بشري", "تحليلات لكل محادثة"],
        techStack: ["OpenAI", "LangChain", "Python", "Vector DB", "Next.js", "Node.js"],
        sortOrder: 6,
      },
      {
        id: "various-apps",
        slug: "various-apps",
        iconName: "LayoutGrid",
        image: "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?q=80&w=900&auto=format&fit=crop",
        accent: "#ea580c",
        titleEn: "Various Apps",
        titleAr: "تطبيقات متنوعة",
        taglineEn: "Booking, delivery, POS, and everything in between.",
        taglineAr: "حجوزات وتوصيل ونقاط بيع وكل ما بينها.",
        descriptionEn: "Purpose-built applications for any workflow — booking systems, delivery apps, POS, portals, and internal tools tailored to how you operate.",
        descriptionAr: "تطبيقات مصممة لأي سير عمل — أنظمة حجز وتطبيقات توصيل ونقاط بيع وبوابات وأدوات داخلية مصممة على طريقة عملك.",
        fullDescriptionEn: "Not every idea fits a template. We design and build custom applications of every kind — restaurant ordering, appointment booking, delivery and logistics, membership portals, and internal dashboards — as fast, reliable products your customers and team actually enjoy using.",
        fullDescriptionAr: "ليست كل فكرة تناسب قالبًا جاهزًا. نصمم ونبني تطبيقات مخصصة من كل نوع — طلبات المطاعم، وحجز المواعيد، والتوصيل واللوجستيات، وبوابات العضوية، ولوحات التحكم الداخلية — كمنتجات سريعة وموثوقة يستمتع عملاؤك وفريقك باستخدامها.",
        deliverablesEn: ["Booking & scheduling apps", "Delivery & logistics apps", "POS & retail systems", "Membership & loyalty portals", "Custom internal tools"],
        deliverablesAr: ["تطبيقات حجز وجدولة", "تطبيقات توصيل ولوجستيات", "أنظمة نقاط بيع وتجزئة", "بوابات عضوية وولاء", "أدوات داخلية مخصصة"],
        featuresEn: ["Built for web and mobile", "Local payment & WhatsApp ready", "Scales with your business", "Bilingual Arabic / English"],
        featuresAr: ["مبني للويب والجوال", "جاهز للدفع المحلي وواتساب", "قابل للتوسع مع نمو عملك", "ثنائي اللغة عربي / إنجليزي"],
        techStack: ["React Native", "Next.js", "Node.js", "PostgreSQL", "Firebase", "KNET"],
        sortOrder: 7,
      },
    ],
  });
  console.log("✅ Services seeded");

  // ─── Testimonials ─────────────────────────────────────────────────────────
  await prisma.testimonial.deleteMany();
  await prisma.testimonial.createMany({
    data: [
      {
        id: "waseet-pools",
        author: "Eng. Mubarak Al-Fadli",
        roleEn: "Managing Director",
        roleAr: "المدير الإداري",
        company: "Waseet Pools Co.",
        location: "Shuwaikh, Kuwait",
        quoteEn: "Burhani Creation understood what we needed and delivered on it. Our SEO and digital presence improved noticeably within a few months.",
        quoteAr: "فهم فريق برهاني كرييشن احتياجاتنا ونفّذها بدقة. تحسّن حضورنا الرقمي وأداء تحسين محركات البحث بشكل ملحوظ خلال أشهر قليلة.",
        rating: 5,
        featured: true,
        sortOrder: 1,
      },
      {
        id: "skinnovation",
        author: "Dr. Reem Al-Sabah",
        roleEn: "Clinical Director",
        roleAr: "المديرة الطبية",
        company: "Skinnovation Clinic",
        location: "Salmiya, Kuwait",
        quoteEn: "The team designed our booking app carefully, sharing interactive wireframes before writing any code. The process was transparent from start to finish.",
        quoteAr: "صمّم الفريق تطبيق الحجز الخاص بنا بعناية، وشاركنا نماذج تفاعلية للواجهة قبل كتابة أي كود. كانت العملية شفافة من البداية للنهاية.",
        rating: 5,
        featured: true,
        sortOrder: 2,
      },
      {
        id: "al-essa-health",
        author: "Tariq Al-Essa",
        roleEn: "Operations Manager",
        roleAr: "مدير العمليات",
        company: "Al-Essa Healthcare Group",
        location: "Kuwait City",
        quoteEn: "They built our e-commerce site with KNET payment integration and automated inventory updates. Our online orders grew significantly in the first quarter.",
        quoteAr: "بنوا موقع التجارة الإلكترونية الخاص بنا مع دمج بوابة كي نت وتحديثات مخزون تلقائية. نما حجم طلباتنا عبر الإنترنت بشكل ملحوظ خلال الربع الأول.",
        rating: 5,
        featured: true,
        sortOrder: 3,
      },
      {
        id: "kerala-express",
        author: "Faisal Al-Kandari",
        roleEn: "Partner",
        roleAr: "شريك",
        company: "Kerala Express Group",
        location: "Hawally, Kuwait",
        quoteEn: "Quick responses and clear communication throughout our app launch. We're happy with how it turned out.",
        quoteAr: "استجابة سريعة وتواصل واضح طوال إطلاق تطبيق الطلبات الخاص بنا. نحن راضون تمامًا عن النتيجة.",
        rating: 5,
        featured: false,
        sortOrder: 4,
      },
    ],
  });
  console.log("✅ Testimonials seeded");

  // ─── Clients ─────────────────────────────────────────────────────────────
  await prisma.client.deleteMany();
  await prisma.client.createMany({
    data: [
      { id: "al-essa", name: "Al-Essa Group", industryEn: "Healthcare & Medical", industryAr: "الرعاية الصحية والطبية", symbol: "AE", sortOrder: 1 },
      { id: "virtus", name: "Virtus Holding", industryEn: "Corporate & Investment", industryAr: "الشركات والاستثمار", symbol: "VH", sortOrder: 2 },
      { id: "skinnovation", name: "Skinnovation Clinic", industryEn: "Derma & Wellness", industryAr: "العناية بالبشرة والعافية", symbol: "SC", sortOrder: 3 },
      { id: "waseet-pools", name: "Waseet Pools Co.", industryEn: "Engineering & Pools", industryAr: "الهندسة والمسابح", symbol: "WP", sortOrder: 4 },
      { id: "kerala-express", name: "Kerala Express", industryEn: "F&B Hospitality", industryAr: "الضيافة والمطاعم", symbol: "KE", sortOrder: 5 },
      { id: "gulf-retail", name: "Gulf Retail Partners", industryEn: "Retail & E-commerce", industryAr: "التجزئة والتجارة الإلكترونية", symbol: "GR", sortOrder: 6 },
      { id: "rifai-complex", name: "Al-Rifai Enterprise", industryEn: "Real Estate & Commercial", industryAr: "العقارات والتجاري", symbol: "RE", sortOrder: 7 },
      { id: "beacon-kw", name: "Beacon Logistics", industryEn: "Supply Chain & Logistics", industryAr: "سلسلة التوريد واللوجستيات", symbol: "BL", sortOrder: 8 },
      { id: "oasis-tech", name: "Oasis Tech Kuwait", industryEn: "IT & Telecommunications", industryAr: "تقنية المعلومات والاتصالات", symbol: "OT", sortOrder: 9 },
    ],
  });
  console.log("✅ Clients seeded");

  // ─── Site Settings ────────────────────────────────────────────────────────
  await prisma.siteSetting.deleteMany();
  await prisma.siteSetting.createMany({
    data: [
      {
        key: "stats",
        value: [
          { value: 170, suffix: "+", labelEn: "Projects delivered", labelAr: "مشروع منجز" },
          { value: 45, suffix: "+", labelEn: "Clients served", labelAr: "عميل تمت خدمته" },
          { value: 4.9, suffix: "/5.0", labelEn: "Average client rating", labelAr: "متوسط تقييم العملاء" },
          { value: 10, suffix: "+", labelEn: "Years in operation", labelAr: "سنوات من الخبرة" },
        ],
      },
      {
        key: "contact",
        value: {
          email: "info@burhanicreation.com",
          phone: "+965 6072 8989",
          whatsapp: "+965 6072 8989",
          address: "Al-Rifai Complex, 9324 Tunisia St, Hawally, Kuwait",
        },
      },
      {
        key: "socials",
        value: {
          instagram: "https://www.instagram.com/burhanicreationkw",
          facebook: "https://www.facebook.com/profile.php?id=100092401885259",
          whatsapp: "https://wa.me/96560728989",
        },
      },
    ],
  });
  console.log("✅ Site settings seeded");

  console.log("🎉 Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
